sudo: required
services:
    - docker

before_install:
    - docker build -t nowert/react-t -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nowert/react-t npm test 

after_success:
    - docker build -t nowertis/multi-client ./client
    - docker build -t nowertis/multi-nginx ./nginx
    - docker build -t nowertis/multi-server ./server
    - docker build -t nowertis/multi-worker ./worker
    #Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push nowertis/multi-client
    - docker push nowertis/multi-nginx
    - docker push nowertis/multi-server
    - docker push nowertis/multi-worker